### ISSUE TITLE
Specific RMBlast version needed?

### ISSUE THREAD

**Issue by oushujun** [Dfam-consortium/RepeatModeler#71]
Hello,

I tried to configure RepeatModeler 2.0.1 using conda installed packages. Others seem to work but the RMBlast path is always dropped by the `configure` script although it indicated "configured" when giving it the path at the beginning.

I tried the `rmblast` installed through the [conda RepeatMasker 4.0.9_p2](https://anaconda.org/bioconda/repeatmasker), and the standalone rmblast from [conda](https://anaconda.org/bioconda/rmblast), and the older versions (v2.2.28 and v2.6.0) of rmblast installed in our server, all indicated succeed by the `configure` script but then dropped (shown un-configured when trying to re-configure).

From the readme there is a precompiled rmblast from [here](http://www.repeatmasker.org/RMBlast.html), it's currently the 2.10.0 version, and it was also not recognized/dropped by the `configure` script.

After the "successful" message from `configure`, if I execute `RepeatModeler` there is an exit error:
>./RepeatModeler 
Can't locate WUBlastSearchEngine.pm in @INC (you may need to install the WUBlastSearchEngine module) (@INC contains: /home/oushujun/las/bin/miniconda2/envs/EDTA/bin /work/LAS/mhufford-lab/oushujun/bin/RepeatModeler /work/LAS/mhufford-lab/oushujun/bin/miniconda2/envs/EDTA/lib/site_perl/5.26.2/x86_64-linux-thread-multi /work/LAS/mhufford-lab/oushujun/bin/miniconda2/envs/EDTA/lib/site_perl/5.26.2 /work/LAS/mhufford-lab/oushujun/bin/miniconda2/envs/EDTA/lib/5.26.2/x86_64-linux-thread-multi /work/LAS/mhufford-lab/oushujun/bin/miniconda2/envs/EDTA/lib/5.26.2 .) at /work/LAS/mhufford-lab/oushujun/bin/RepeatModeler/RepeatUtil.pm line 78.
BEGIN failed--compilation aborted at /work/LAS/mhufford-lab/oushujun/bin/RepeatModeler/RepeatUtil.pm line 78.
Compilation failed in require at ./RepeatModeler line 126.
BEGIN failed--compilation aborted at ./RepeatModeler line 126.

At this point I am not sure if a special RMBlast is required or something wrong with the `configure` script.

Thanks,
Shujun

**Comment by jebrosen** [comment]
In RepeatModeler 2.0.1 we had to drop support for RMBlast older than 2.9.0. It should work fine with 2.9.0(-p2) and 2.10.0.

> all indicated succeed by the configure script but then dropped (shown un-configured when trying to re-configure).

We recently got a report of this by e-mail as well. Re-running the `configure` program "forgets" the configured search engines. To verify that the paths have been set, you can check them in `RepModelConfig.pm` instead of re-running `configure`.

> ./RepeatModeler
> Can't locate WUBlastSearchEngine.pm

This error occurs because RepeatModeler uses perl modules from RepeatMasker, which is why it needs to know the RepeatMasker directory. However none of the directories in `@inc` looks like a RepeatMasker directory - if you installed RepeatMasker through conda, the correct directory would be something like `.../conda/.../share/RepeatMasker/`. It looks like you might have specified `/home/oushujun/las/bin/miniconda2/envs/EDTA/bin` as the path to RepeatMasker, which would have "tricked" `configure` into accepting it incorrectly.

We should fix `configure` so that it looks for some of those perl modules, not just the main `RepeatMasker` script to avoid that in the future.

**Comment by oushujun** [comment]
Fixing the RepeatMasker path works (with RMBlast v2.9.0). 

I got the path `/home/oushujun/las/bin/miniconda2/envs/EDTA/bin` of the conda-installed RepeatMasker using `which RepeatMasker`. It went through the `configure` script check but reported error by the program. By changing the RepeatMasker path to this one 
`/home/oushujun/las/bin/miniconda2/envs/EDTA/share/RepeatMasker/`, it works.

I agree that the `configure` script should also look for the dependent Perl modules from the user provided RepeatMasker path.

**Comment by splaisan** [comment]
HI,
I am trying to install RepeatModeler in conda as the `dfam/tetools:latest` docker image only works as root and does not allow `-u "$(id -u):$(id -g)"`

```
conda create -n repeatmodeler
conda activate repeatmodeler
conda install -c bioconda repeatmodeler
```

I get a lot of error messages suggesting multiple package source conflicts

```
Channels:
 - bioconda
 - defaults
 - conda-forge
 - r
 - anaconda
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/miniconda3/envs/repeatmodeler

  added / updated specs:
    - repeatmodeler


The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge 
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-2_gnu 
  biopython          pkgs/main/linux-64::biopython-1.78-py39h7f8727e_0 
  blas               pkgs/main/linux-64::blas-1.0-openblas 
  blast              bioconda/linux-64::blast-2.15.0-pl5321h6f7f691_1 
  bz2file            pkgs/main/linux-64::bz2file-0.98-py39h06a4308_1 
  bzip2              pkgs/main/linux-64::bzip2-1.0.8-h7b6447c_0 
  c-ares             pkgs/main/linux-64::c-ares-1.19.1-h5eee18b_0 
  ca-certificates    pkgs/main/linux-64::ca-certificates-2023.08.22-h06a4308_0 
  cairo              pkgs/main/linux-64::cairo-1.16.0-hb05425b_5 
  cd-hit             bioconda/linux-64::cd-hit-4.8.1-h43eeafb_9 
  curl               pkgs/main/linux-64::curl-8.2.1-h37d81fd_0 
  drmaa              pkgs/main/linux-64::drmaa-0.7.9-py39h06a4308_0 
  entrez-direct      bioconda/linux-64::entrez-direct-16.2-he881be0_1 
  expat              pkgs/main/linux-64::expat-2.5.0-h6a678d5_0 
  font-ttf-dejavu-s~ pkgs/main/noarch::font-ttf-dejavu-sans-mono-2.37-hd3eb1b0_0 
  font-ttf-inconsol~ pkgs/main/noarch::font-ttf-inconsolata-2.001-hcb22688_0 
  font-ttf-source-c~ pkgs/main/noarch::font-ttf-source-code-pro-2.030-hd3eb1b0_0 
  font-ttf-ubuntu    pkgs/main/noarch::font-ttf-ubuntu-0.83-h8b1ccd4_0 
  fontconfig         conda-forge/linux-64::fontconfig-2.14.2-h14ed4e7_0 
  fonts-anaconda     pkgs/main/noarch::fonts-anaconda-1-h8fa9717_0 
  fonts-conda-ecosy~ pkgs/main/noarch::fonts-conda-ecosystem-1-hd3eb1b0_0 
  freetype           pkgs/main/linux-64::freetype-2.12.1-h4a9f257_0 
  fribidi            pkgs/main/linux-64::fribidi-1.0.10-h7b6447c_0 
  gawk               pkgs/main/linux-64::gawk-5.1.0-h7b6447c_0 
  genometools-genom~ bioconda/linux-64::genometools-genometools-1.6.4-py39h58cc16e_0 
  gettext            conda-forge/linux-64::gettext-0.21.1-h27087fc_0 
  glib               conda-forge/linux-64::glib-2.78.1-hfc55251_1 
  glib-tools         conda-forge/linux-64::glib-tools-2.78.1-hfc55251_1 
  graphite2          pkgs/main/linux-64::graphite2-1.3.14-h295c915_1 
  h5py               pkgs/main/linux-64::h5py-3.9.0-py39he06866b_0 
  harfbuzz           conda-forge/linux-64::harfbuzz-6.0.0-h8e241bc_0 
  hdf5               pkgs/main/linux-64::hdf5-1.12.1-h70be1eb_2 
  hmmer              bioconda/linux-64::hmmer-3.4-hdbdd923_0 
  icu                conda-forge/linux-64::icu-70.1-h27087fc_0 
  krb5               pkgs/main/linux-64::krb5-1.20.1-h568e23c_1 
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.38-h1181459_1 
  libcurl            pkgs/main/linux-64::libcurl-8.2.1-h91b91d3_0 
  libedit            pkgs/main/linux-64::libedit-3.1.20221030-h5eee18b_0 
  libev              pkgs/main/linux-64::libev-4.33-h7f8727e_1 
  libffi             pkgs/main/linux-64::libffi-3.4.4-h6a678d5_0 
  libgcc-ng          conda-forge/linux-64::libgcc-ng-13.2.0-h807b86a_3 
  libgfortran-ng     pkgs/main/linux-64::libgfortran-ng-11.2.0-h00389a5_1 
  libgfortran5       pkgs/main/linux-64::libgfortran5-11.2.0-h1234567_1 
  libglib            conda-forge/linux-64::libglib-2.78.1-h783c2da_1 
  libgomp            conda-forge/linux-64::libgomp-13.2.0-h807b86a_3 
  libiconv           conda-forge/linux-64::libiconv-1.17-h166bdaf_0 
  libidn2            pkgs/main/linux-64::libidn2-2.3.4-h5eee18b_0 
  libnghttp2         pkgs/main/linux-64::libnghttp2-1.52.0-ha637b67_1 
  libnsl             pkgs/main/linux-64::libnsl-2.0.0-h5eee18b_0 
  libopenblas        pkgs/main/linux-64::libopenblas-0.3.21-h043d6bf_0 
  libpng             pkgs/main/linux-64::libpng-1.6.39-h5eee18b_0 
  libsqlite          conda-forge/linux-64::libsqlite-3.44.2-h2797004_0 
  libssh2            pkgs/main/linux-64::libssh2-1.10.0-h37d81fd_2 
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-13.2.0-h7e041cc_3 
  libunistring       pkgs/main/linux-64::libunistring-0.9.10-h27cfd23_0 
  libuuid            conda-forge/linux-64::libuuid-2.38.1-h0b41bf4_0 
  libxcb             pkgs/main/linux-64::libxcb-1.15-h7f8727e_0 
  libxml2            conda-forge/linux-64::libxml2-2.9.14-h22db469_4 
  libzlib            conda-forge/linux-64::libzlib-1.2.13-hd590300_5 
  ltr_retriever      bioconda/noarch::ltr_retriever-2.9.4-hdfd78af_0 
  mafft              bioconda/linux-64::mafft-7.520-h031d066_3 
  mysql-connector-c  pkgs/main/linux-64::mysql-connector-c-6.1.11-h24aacaa_2 
  ncbi-vdb           bioconda/linux-64::ncbi-vdb-3.0.9-hdbdd923_0 
  ncurses            pkgs/main/linux-64::ncurses-6.4-h6a678d5_0 
  ninja-nj           bioconda/linux-64::ninja-nj-0.98-h4ac6f70_3 
  nseg               bioconda/linux-64::nseg-1.0.1-h031d066_4 
  numpy              pkgs/main/linux-64::numpy-1.26.0-py39heeff2f4_0 
  numpy-base         pkgs/main/linux-64::numpy-base-1.26.0-py39h8a23956_0 
  openssl            pkgs/main/linux-64::openssl-1.1.1w-h7f8727e_0 
  ossuuid            conda-forge/linux-64::ossuuid-1.6.2-hf484d3e_1000 
  pango              conda-forge/linux-64::pango-1.50.14-hd33c08f_0 
  pcre               pkgs/main/linux-64::pcre-8.45-h295c915_0 
  pcre2              pkgs/main/linux-64::pcre2-10.42-hebb0a14_0 
  perl               pkgs/main/linux-64::perl-5.32.1-0_h5eee18b_perl5 
  perl-alien-build   bioconda/linux-64::perl-alien-build-2.48-pl5321hec16e2b_0 
  perl-alien-libxml2 bioconda/linux-64::perl-alien-libxml2-0.17-pl5321hec16e2b_0 
  perl-archive-tar   bioconda/noarch::perl-archive-tar-2.40-pl5321hdfd78af_0 
  perl-base          bioconda/noarch::perl-base-2.23-pl5321hdfd78af_2 
  perl-business-isbn bioconda/noarch::perl-business-isbn-3.007-pl5321hdfd78af_0 
  perl-business-isb~ bioconda/noarch::perl-business-isbn-data-20210112.006-pl5321hdfd78af_0 
  perl-capture-tiny  bioconda/noarch::perl-capture-tiny-0.48-pl5321hdfd78af_2 
  perl-carp          bioconda/noarch::perl-carp-1.38-pl5321hdfd78af_4 
  perl-common-sense  bioconda/noarch::perl-common-sense-3.75-pl5321hdfd78af_0 
  perl-compress-raw~ bioconda/linux-64::perl-compress-raw-bzip2-2.201-pl5321h87f3376_1 
  perl-compress-raw~ bioconda/linux-64::perl-compress-raw-zlib-2.105-pl5321h87f3376_0 
  perl-constant      bioconda/noarch::perl-constant-1.33-pl5321hdfd78af_2 
  perl-data-dumper   bioconda/linux-64::perl-data-dumper-2.183-pl5321hec16e2b_1 
  perl-devel-size    bioconda/linux-64::perl-devel-size-0.83-pl5321h031d066_4 
  perl-digest-hmac   bioconda/noarch::perl-digest-hmac-1.04-pl5321hdfd78af_0 
  perl-digest-md5    bioconda/linux-64::perl-digest-md5-2.58-pl5321hec16e2b_1 
  perl-encode        bioconda/linux-64::perl-encode-3.19-pl5321hec16e2b_1 
  perl-encode-locale bioconda/noarch::perl-encode-locale-1.05-pl5321hdfd78af_7 
  perl-exporter      bioconda/noarch::perl-exporter-5.72-pl5321hdfd78af_2 
  perl-exporter-tiny bioconda/noarch::perl-exporter-tiny-1.002002-pl5321hdfd78af_0 
  perl-extutils-mak~ conda-forge/noarch::perl-extutils-makemaker-7.70-pl5321hd8ed1ab_0 
  perl-ffi-checklib  bioconda/noarch::perl-ffi-checklib-0.28-pl5321hdfd78af_0 
  perl-file-chdir    bioconda/noarch::perl-file-chdir-0.1010-pl5321hdfd78af_3 
  perl-file-listing  bioconda/noarch::perl-file-listing-6.16-pl5321hdfd78af_0 
  perl-file-path     conda-forge/noarch::perl-file-path-2.18-pl5321hd8ed1ab_0 
  perl-file-spec     bioconda/noarch::perl-file-spec-3.48_01-pl5321hdfd78af_2 
  perl-file-temp     conda-forge/noarch::perl-file-temp-0.2304-pl5321hd8ed1ab_0 
  perl-file-which    conda-forge/noarch::perl-file-which-1.24-pl5321hd8ed1ab_0 
  perl-html-parser   bioconda/linux-64::perl-html-parser-3.81-pl5321h4ac6f70_1 
  perl-html-tagset   bioconda/noarch::perl-html-tagset-3.20-pl5321hdfd78af_4 
  perl-http-cookies  bioconda/noarch::perl-http-cookies-6.10-pl5321hdfd78af_0 
  perl-http-daemon   bioconda/noarch::perl-http-daemon-6.16-pl5321hdfd78af_0 
  perl-http-date     bioconda/noarch::perl-http-date-6.06-pl5321hdfd78af_0 
  perl-http-message  bioconda/noarch::perl-http-message-6.36-pl5321hdfd78af_0 
  perl-http-negotia~ bioconda/noarch::perl-http-negotiate-6.01-pl5321hdfd78af_4 
  perl-importer      bioconda/noarch::perl-importer-0.026-pl5321hdfd78af_0 
  perl-io-compress   bioconda/linux-64::perl-io-compress-2.201-pl5321hdbdd923_2 
  perl-io-html       bioconda/noarch::perl-io-html-1.004-pl5321hdfd78af_0 
  perl-io-socket-ssl bioconda/noarch::perl-io-socket-ssl-2.074-pl5321hdfd78af_0 
  perl-io-zlib       bioconda/noarch::perl-io-zlib-1.14-pl5321hdfd78af_0 
  perl-json          bioconda/noarch::perl-json-4.10-pl5321hdfd78af_0 
  perl-json-xs       bioconda/linux-64::perl-json-xs-2.34-pl5321h4ac6f70_6 
  perl-libwww-perl   bioconda/noarch::perl-libwww-perl-6.67-pl5321hdfd78af_0 
  perl-list-moreuti~ bioconda/noarch::perl-list-moreutils-0.430-pl5321hdfd78af_0 
  perl-list-moreuti~ bioconda/linux-64::perl-list-moreutils-xs-0.430-pl5321h031d066_2 
  perl-lwp-mediatyp~ bioconda/noarch::perl-lwp-mediatypes-6.04-pl5321hdfd78af_1 
  perl-mime-base64   bioconda/linux-64::perl-mime-base64-3.16-pl5321hec16e2b_2 
  perl-net-http      bioconda/noarch::perl-net-http-6.22-pl5321hdfd78af_0 
  perl-net-ssleay    bioconda/linux-64::perl-net-ssleay-1.92-pl5321h0e0aaa8_1 
  perl-ntlm          bioconda/noarch::perl-ntlm-1.09-pl5321hdfd78af_5 
  perl-parent        bioconda/noarch::perl-parent-0.236-pl5321hdfd78af_2 
  perl-path-tiny     bioconda/noarch::perl-path-tiny-0.122-pl5321hdfd78af_0 
  perl-pathtools     bioconda/linux-64::perl-pathtools-3.75-pl5321hec16e2b_3 
  perl-scalar-list-~ bioconda/linux-64::perl-scalar-list-utils-1.62-pl5321hec16e2b_1 
  perl-scope-guard   bioconda/noarch::perl-scope-guard-0.21-pl5321hdfd78af_3 
  perl-socket        bioconda/linux-64::perl-socket-2.027-pl5321h031d066_4 
  perl-storable      bioconda/linux-64::perl-storable-3.15-pl5321hec16e2b_3 
  perl-sub-info      bioconda/noarch::perl-sub-info-0.002-pl5321hdfd78af_1 
  perl-term-table    bioconda/noarch::perl-term-table-0.016-pl5321hdfd78af_0 
  perl-test-simple   bioconda/noarch::perl-test-simple-1.302190-pl5321hdfd78af_0 
  perl-test2-suite   bioconda/noarch::perl-test2-suite-0.000145-pl5321hdfd78af_0 
  perl-text-soundex  conda-forge/noarch::perl-text-soundex-3.05-pl5321hd8ed1ab_1001 
  perl-time-local    bioconda/noarch::perl-time-local-1.35-pl5321hdfd78af_0 
  perl-timedate      bioconda/noarch::perl-timedate-2.33-pl5321hdfd78af_2 
  perl-try-tiny      bioconda/noarch::perl-try-tiny-0.31-pl5321hdfd78af_1 
  perl-types-serial~ bioconda/noarch::perl-types-serialiser-1.01-pl5321hdfd78af_0 
  perl-uri           bioconda/noarch::perl-uri-5.12-pl5321hdfd78af_0 
  perl-url-encode    bioconda/linux-64::perl-url-encode-0.03-pl5321h9ee0642_0 
  perl-www-robotrul~ bioconda/noarch::perl-www-robotrules-6.02-pl5321hdfd78af_4 
  perl-xml-libxml    bioconda/linux-64::perl-xml-libxml-2.0207-pl5321h661654b_0 
  perl-xml-namespac~ bioconda/noarch::perl-xml-namespacesupport-1.12-pl5321hdfd78af_1 
  perl-xml-sax       bioconda/noarch::perl-xml-sax-1.02-pl5321hdfd78af_1 
  perl-xml-sax-base  bioconda/noarch::perl-xml-sax-base-1.09-pl5321hdfd78af_1 
  pip                pkgs/main/linux-64::pip-23.3.1-py39h06a4308_0 
  pixman             pkgs/main/linux-64::pixman-0.40.0-h7f8727e_1 
  pp                 bioconda/noarch::pp-1.6.4.4-py_0 
  python             pkgs/main/linux-64::python-3.9.18-h7a1cb2a_0 
  python_abi         conda-forge/linux-64::python_abi-3.9-2_cp39 
  readline           pkgs/main/linux-64::readline-8.2-h5eee18b_0 
  recon              bioconda/linux-64::recon-1.08-h031d066_6 
  repeatmasker       bioconda/noarch::repeatmasker-4.1.5-pl5321hdfd78af_1 
  repeatmodeler      bioconda/noarch::repeatmodeler-2.0.5-pl5321hdfd78af_0 
  repeatscout        bioconda/linux-64::repeatscout-1.0.6-hec16e2b_3 
  rmblast            bioconda/linux-64::rmblast-2.14.1-h4565617_0 
  setuptools         pkgs/main/linux-64::setuptools-68.0.0-py39h06a4308_0 
  six                pkgs/main/noarch::six-1.16.0-pyhd3eb1b0_1 
  sqlite             pkgs/main/linux-64::sqlite-3.41.2-h5eee18b_0 
  tesorter           bioconda/noarch::tesorter-1.4.6-pyhdfd78af_0 
  tk                 pkgs/main/linux-64::tk-8.6.12-h1ccaba5_0 
  trf                bioconda/linux-64::trf-4.09.1-h031d066_4 
  tzdata             pkgs/main/noarch::tzdata-2023c-h04d1e81_0 
  ucsc-fatotwobit    bioconda/linux-64::ucsc-fatotwobit-447-h954228d_0 
  ucsc-twobitinfo    bioconda/linux-64::ucsc-twobitinfo-447-h954228d_0 
  ucsc-twobittofa    bioconda/linux-64::ucsc-twobittofa-447-h954228d_0 
  wget               pkgs/main/linux-64::wget-1.21.4-h91b91d3_1 
  wheel              pkgs/main/linux-64::wheel-0.41.2-py39h06a4308_0 
  xopen              bioconda/noarch::xopen-0.7.3-py_0 
  xorg-kbproto       conda-forge/linux-64::xorg-kbproto-1.0.7-h7f98852_1002 
  xorg-libice        conda-forge/linux-64::xorg-libice-1.1.1-hd590300_0 
  xorg-libsm         conda-forge/linux-64::xorg-libsm-1.2.4-h7391055_0 
  xorg-libx11        conda-forge/linux-64::xorg-libx11-1.8.7-h8ee46fc_0 
  xorg-libxext       conda-forge/linux-64::xorg-libxext-1.3.4-h0b41bf4_2 
  xorg-libxrender    conda-forge/linux-64::xorg-libxrender-0.9.11-hd590300_0 
  xorg-renderproto   conda-forge/linux-64::xorg-renderproto-0.11.1-h7f98852_1002 
  xorg-xextproto     conda-forge/linux-64::xorg-xextproto-7.3.0-h0b41bf4_1003 
  xorg-xproto        pkgs/main/linux-64::xorg-xproto-7.0.31-h27cfd23_1007 
  xz                 pkgs/main/linux-64::xz-5.4.2-h5eee18b_0 
  zlib               conda-forge/linux-64::zlib-1.2.13-hd590300_5 


Proceed ([y]/n)? y


Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: \ 
SafetyError: The package for repeatmasker located at /opt/miniconda3/pkgs/repeatmasker-4.1.5-pl5321hdfd78af_1
appears to be corrupted. The path 'share/RepeatMasker/Libraries/Dfam.h5'
has an incorrect size.
  reported size: 68 bytes
  actual size: 1593452770 bytes

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::libuuid-2.38.1-h0b41bf4_0, conda-forge/linux-64::ossuuid-1.6.2-hf484d3e_1000
  path: 'lib/libuuid.a'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::libuuid-2.38.1-h0b41bf4_0, conda-forge/linux-64::ossuuid-1.6.2-hf484d3e_1000
  path: 'lib/libuuid.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::libuuid-2.38.1-h0b41bf4_0, conda-forge/linux-64::ossuuid-1.6.2-hf484d3e_1000
  path: 'lib/pkgconfig/uuid.pc'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::libsqlite-3.44.2-h2797004_0, defaults/linux-64::sqlite-3.41.2-h5eee18b_0
  path: 'include/sqlite3.h'

```

can you please help me
thanks
